WITH modeling_data AS (
    SELECT
        -- Labels from real_performance
        real_perf.goals AS label_goals,
        real_perf.assists AS label_assists,

        -- Columns from pre
        pre.player_id,
        pre.fix_id,
        pre.game_week,
        pre.season,
        pre.team_strength,
        pre.opponent_strength,
        pre.rolling_ub_minutes,
        pre.rolling_ub_np_expected_goals,
        pre.rolling_ub_expected_goals,
        pre.rolling_ub_goals,
        pre.rolling_ub_expected_assists,
        pre.rolling_ub_assists,
        pre.rolling_ub_shots,
        pre.rolling_ub_shots_on_target,
        pre.rolling_ub_pk_made,
        pre.rolling_ub_pk_attempt,
        pre.rolling_ub_yellow_cards,
        pre.rolling_ub_red_cards,
        pre.rolling_ub_touches,
        pre.rolling_ub_tackles,
        pre.rolling_ub_interceptions,
        pre.rolling_ub_blocks,
        pre.rolling_ub_shot_creating_actions,
        pre.rolling_ub_goal_creating_actions,
        pre.rolling_ub_pass_attempted,
        pre.rolling_ub_pass_completed,
        pre.rolling_ub_pass_progressive,
        pre.rolling_ub_carries,
        pre.rolling_ub_carries_progressive,
        pre.rolling_ub_take_ons_attempted,
        pre.rolling_ub_take_ons_success,
        pre.rolling_bound_last3_minutes,
        pre.rolling_bound_last3_expected_goals,
        pre.rolling_bound_last3_np_expected_goals,
        pre.rolling_bound_last3_expected_assists,
        pre.rolling_bound_last3_goals,
        pre.rolling_bound_last3_assists,
        pre.rolling_bound_last3_shots,
        pre.rolling_bound_last3_pk_made,
        pre.rolling_bound_last3_pk_attempt,
        pre.rolling_bound_last3_shots_on_target,
        pre.rolling_bound_last3_yellow_cards,
        pre.rolling_bound_last3_red_cards,
        pre.rolling_bound_last3_touches,
        pre.rolling_bound_last3_tackles,
        pre.rolling_bound_last3_interceptions,
        pre.rolling_bound_last3_blocks,
        pre.rolling_bound_last3_shot_creating_actions,
        pre.rolling_bound_last3_goal_creating_actions,
        pre.rolling_bound_last3_pass_completed,
        pre.rolling_bound_last3_pass_attempted,
        pre.rolling_bound_last3_pass_progressive,
        pre.rolling_bound_last3_carries,
        pre.rolling_bound_last3_carries_progressive,
        pre.rolling_bound_last3_take_ons_attempted,
        pre.rolling_bound_last3_take_ons_success,
        pre.rolling_bound_last6_minutes,
        pre.rolling_bound_last6_expected_goals,
        pre.rolling_bound_last6_np_expected_goals,
        pre.rolling_bound_last6_expected_assists,
        pre.rolling_bound_last6_goals,
        pre.rolling_bound_last6_assists,
        pre.rolling_bound_last6_shots,
        pre.rolling_bound_last6_pk_made,
        pre.rolling_bound_last6_pk_attempt,
        pre.rolling_bound_last6_shots_on_target,
        pre.rolling_bound_last6_yellow_cards,
        pre.rolling_bound_last6_red_cards,
        pre.rolling_bound_last6_touches,
        pre.rolling_bound_last6_tackles,
        pre.rolling_bound_last6_interceptions,
        pre.rolling_bound_last6_blocks,
        pre.rolling_bound_last6_shot_creating_actions,
        pre.rolling_bound_last6_goal_creating_actions,
        pre.rolling_bound_last6_pass_completed,
        pre.rolling_bound_last6_pass_attempted,
        pre.rolling_bound_last6_pass_progressive,
        pre.rolling_bound_last6_carries,
        pre.rolling_bound_last6_carries_progressive,
        pre.rolling_bound_last6_take_ons_attempted,
        pre.rolling_bound_last6_take_ons_success,
        pre.goals_efficiency_ub,
        pre.assists_efficiency_ub,
        pre.shots_efficiency_ub,
        pre.contribution_real_ub,
        pre.contribution_xgi_ub,
        pre.contribution_npxgi_ub,
        pre.contribution_efficiency_xgi_ub,
        pre.contribution_efficiency_npxgi_ub,
        pre.goals_efficiency_last3,
        pre.assists_efficiency_last3,
        pre.shots_efficiency_last3,
        pre.contribution_real_last3,
        pre.contribution_xgi_last3,
        pre.contribution_npxgi_last3,
        pre.contribution_efficiency_xgi_last3,
        pre.contribution_efficiency_npxgi_last3,
        pre.goals_per_90_ub,
        pre.assists_per_90_ub,
        pre.real_contribution_per_90_ub,
        pre.xg_per_90_ub,
        pre.npxg_per_90_ub,
        pre.xa_per_90_ub,
        pre.xgi_per_90_ub,
        pre.npxgi_per_90_ub,
        pre.shots_per_90_ub,
        pre.shots_on_target_per_90_ub,
        pre.shot_creating_actions_per_90_ub,
        pre.goal_creating_actions_per_90_ub,
        pre.goals_per_90_last3,
        pre.assists_per_90_last3,
        pre.real_contribution_per_90_last3,
        pre.xg_per_90_last3,
        pre.npxg_per_90_last3,
        pre.xa_per_90_last3,
        pre.xgi_per_90_last3,
        pre.npxgi_per_90_last3,
        pre.shots_per_90_last3,
        pre.shots_on_target_per_90_last3,
        pre.shot_creating_actions_per_90_last3,
        pre.goal_creating_actions_per_90_last3,

        -- Columns from team_pre
        team_pre.rolling_goals_scored_last3,
        team_pre.rolling_goals_conceded_last3,
        team_pre.rolling_goals_scored_last6,
        team_pre.rolling_goals_conceded_last6,
        team_pre.rolling_goals_scored_ub,
        team_pre.rolling_goals_conceded_ub

    FROM {{ ref('fct_outf_player_pre_match') }} pre
    JOIN {{ ref('real_performance') }} real_perf
        ON pre.player_id = real_perf.player_id
        AND pre.fix_id = real_perf.fix_id
    JOIN {{ ref('fct_team_pre_match') }} team_pre
        ON pre.team_id = team_pre.team_id
        AND pre.fix_id = team_pre.fix_id
    WHERE pre.rolling_ub_minutes >= 60
)

SELECT *
FROM modeling_data